#pragma once
#include <cstdint>
#include <memory>
#include <string>
#include <rust/cxx.h>
#include <kiwix/book.h>
#include <kiwix/library.h>
#include <kiwix/manager.h>
#include <kiwix/server.h>

std::shared_ptr<kiwix::Library> create_library();
std::shared_ptr<kiwix::Book> create_book();

std::shared_ptr<kiwix::Filter> create_filter();
kiwix::Filter& filter_valid(kiwix::Filter& filter, bool accept);
kiwix::Filter& filter_local(kiwix::Filter& filter, bool accept);
kiwix::Filter& filter_remote(kiwix::Filter& filter, bool accept);
kiwix::Filter& filter_query(kiwix::Filter& filter, rust::Str query);
kiwix::Filter& filter_lang(kiwix::Filter& filter, rust::Str lang);
kiwix::Filter& filter_category(kiwix::Filter& filter, rust::Str category);
kiwix::Filter& filter_name(kiwix::Filter& filter, rust::Str name);
kiwix::Filter& filter_accept_tags(kiwix::Filter& filter, const rust::Vec<rust::String>& tags);
kiwix::Filter& filter_reject_tags(kiwix::Filter& filter, const rust::Vec<rust::String>& tags);
kiwix::Filter& filter_max_size(kiwix::Filter& filter, size_t size);

bool filter_has_query(const kiwix::Filter& filter);
rust::String filter_get_query(const kiwix::Filter& filter);
bool filter_has_lang(const kiwix::Filter& filter);
rust::String filter_get_lang(const kiwix::Filter& filter);
bool filter_has_category(const kiwix::Filter& filter);
rust::String filter_get_category(const kiwix::Filter& filter);

rust::Vec<rust::String> library_filter(kiwix::Library& library, const kiwix::Filter& filter);

void book_set_path(kiwix::Book& book, rust::Str path);
bool library_add_book(kiwix::Library& library, const kiwix::Book& book);

rust::String library_add_book_from_path(kiwix::Library& library, rust::Str path);
std::shared_ptr<kiwix::Book> library_get_book_by_id(kiwix::Library& library, rust::Str id);

rust::String book_get_id(const kiwix::Book& book);
rust::String book_get_name(const kiwix::Book& book);
rust::String book_get_date(const kiwix::Book& book);
rust::String book_get_flavour(const kiwix::Book& book);
rust::String book_get_title(const kiwix::Book& book);
rust::String book_get_description(const kiwix::Book& book);
rust::String book_get_language(const kiwix::Book& book);
rust::String book_get_creator(const kiwix::Book& book);
rust::String book_get_publisher(const kiwix::Book& book);
rust::String book_get_category(const kiwix::Book& book);
rust::String book_get_tags(const kiwix::Book& book);
rust::String book_get_url(const kiwix::Book& book);
uint64_t book_get_article_count(const kiwix::Book& book);
uint64_t book_get_media_count(const kiwix::Book& book);
uint64_t book_get_size(const kiwix::Book& book);
bool book_is_path_valid(const kiwix::Book& book);

// Forward declaration of the shared struct generated by CXX.
struct BookIllustration;

rust::Vec<BookIllustration> book_get_illustrations(const kiwix::Book& book);

std::shared_ptr<kiwix::Server> create_server(std::shared_ptr<kiwix::Library> library);

void server_set_address(kiwix::Server& server, rust::Str address);
void server_set_port(kiwix::Server& server, int port);
void server_set_ip_mode(kiwix::Server& server, std::int32_t mode);
bool server_start(kiwix::Server& server);
void server_stop(kiwix::Server& server);
